tap "anomalyco/tap"
tap "facebook/fb"
tap "gromgit/fuse"
tap "heroku/brew"
tap "microsoft/mssql-release"
tap "mistertea/et"
tap "mongodb/brew"
tap "phrase/brewed"
tap "snyk/tap"
tap "teamookla/speedtest"
tap "wix/brew"

# --- Core CLI (dev_cli category) ---
brew "bash"
brew "coreutils"
brew "chezmoi"
brew "gh"
brew "git"
brew "git-filter-repo"
brew "git-lfs"
brew "go"
brew "htop"
brew "jq"
brew "make"
brew "node"
brew "nvm"
brew "p7zip"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "zellij"
brew "uv"
brew "wget"
brew "yq"

# --- Shared tap formulas ---
brew "anomalyco/tap/opencode"
brew "facebook/fb/idb-companion"
brew "gromgit/fuse/ext2fuse-mac"
brew "gromgit/fuse/ext4fuse-mac"
brew "gromgit/fuse/ntfs-3g-mac"
brew "gromgit/fuse/s3fs-mac"
brew "heroku/brew/heroku"
brew "microsoft/mssql-release/msodbcsql18"
brew "microsoft/mssql-release/mssql-tools18"
brew "mistertea/et/et"
brew "mongodb/brew/mongodb-database-tools"
brew "mongodb/brew/mongodb-community"
brew "phrase/brewed/phraseapp"
brew "snyk/tap/snyk"
brew "teamookla/speedtest/speedtest"
brew "wix/brew/applesimutils"

# --- npm ---
npm "corepack"
