#!/usr/bin/env python3
"""Remove project-scoped AI-tooling artefacts generated by configure-project.py."""

import argparse
import json
import os
from pathlib import Path
import shutil
import sys

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
LIB_DIR = os.path.join(SCRIPT_DIR, "lib")
sys.path.insert(0, LIB_DIR)

import logger
from cli_helpers import add_common_args, add_skip_arg, parse_skip
from env import load_env
from skills_manifest import CANONICAL_STORE

ALL_STEPS = [
    "opencode",
    "tier",
    "codegraph",
    "mcps",
    "skills",
    "jetbrains",
    "junie",
    "pi",
    "acp-agents",
    "secrets",
]


def csv(value):
    """Parse a comma-separated option."""
    return [item.strip() for item in (value or "").split(",") if item.strip()]


def _action(kind, path, reason, safety_class):
    return {
        "kind": kind,
        "path": str(path),
        "reason": reason,
        "safety_class": safety_class,
    }


def _add(actions, seen, kind, path, reason, safety_class="generated"):
    path = Path(path)
    if str(path) not in seen and (path.is_symlink() or path.exists()):
        actions.append(_action(kind, path, reason, safety_class))
        seen.add(str(path))


def _known_mcp_names():
    registry = Path(SCRIPT_DIR).parent / "configs" / "mcp" / "global-mcps.json"
    with registry.open(encoding="utf-8") as handle:
        data = json.load(handle)
    names = set(data.get("project_mcp_templates", []))
    for tool in data.get("tools", {}).values():
        for server in tool.get("mcp_servers", []):
            names.add(server.get("name_override", server.get("template")))
    # In project mode resolve_defs_list ignores name_override and uses each
    # template's internal "name" field, which can differ from the filename
    # (e.g. mongodb.json -> "MongoDB", notion.json -> "Notion"). Collect the
    # actual emitted server names too.
    templates_dir = Path(SCRIPT_DIR).parent / "configs" / "mcp" / "templates"
    for name in sorted(names):
        template = templates_dir / f"{name}.json"
        try:
            with template.open(encoding="utf-8") as handle:
                internal = json.load(handle).get("name")
        except (OSError, ValueError):
            continue
        if internal:
            names.add(internal)
    return {name for name in names if name}


def _merge_file_is_generated(path, names):
    try:
        with path.open(encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return False
    if not isinstance(data, dict):
        return False
    containers = []
    for key in ("mcpServers", "servers"):
        if isinstance(data.get(key), dict):
            containers.append(key)
    if not containers:
        return False
    remaining = {key: value for key, value in data.items() if key not in containers}
    for key in containers:
        servers = data[key]
        remaining_servers = {
            name: value for name, value in servers.items() if name not in names
        }
        if remaining_servers:
            return False
    return not remaining


def _root_opencode_generated(path):
    if path.is_symlink():
        return False
    try:
        with path.open(encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return False
    # Project-mode configure-opencode.py always emits disabled_providers; a
    # minimal hand-authored override (e.g. just $schema + model) does not.
    return isinstance(data, dict) and "disabled_providers" in data


def plan_cleanup(root, steps):
    """Return safe, filesystem-aware cleanup actions for *root* and *steps*."""
    root = Path(root).resolve()
    steps = set(steps)
    actions, seen = [], set()
    opencode = root / ".opencode"

    if "opencode" in steps:
        root_config = root / "opencode.json"
        if _root_opencode_generated(root_config):
            _add(
                actions, seen, "file", root_config, "generated project OpenCode config"
            )
        elif root_config.exists() or root_config.is_symlink():
            logger.warning(
                "Keeping unmarked or symlinked root OpenCode config: %s", root_config
            )
        _add(
            actions,
            seen,
            "dir",
            opencode / ".tmp-opencode",
            "generated OpenCode temporary directory",
        )
    if "skills" in steps:
        _add(
            actions,
            seen,
            "file",
            opencode / "opencode.json",
            "generated skill-deny OpenCode config",
        )
    if "tier" in steps or "acp-agents" in steps or "secrets" in steps:
        for name, owner in (
            ("oh-my-opencode-slim.json", "tier"),
            ("acp-agents.json", "acp-agents"),
            (".env.local", "secrets"),
        ):
            if owner in steps:
                _add(
                    actions,
                    seen,
                    "file",
                    opencode / name,
                    f"generated {owner} artifact",
                )
    if any(
        step in steps
        for step in ("opencode", "skills", "tier", "acp-agents", "secrets")
    ):
        _add(
            actions,
            seen,
            "dir-if-empty",
            opencode,
            "project OpenCode directory (only when empty)",
        )
    if "skills" in steps:
        skills = opencode / "skills"
        if skills.is_dir() and not skills.is_symlink():
            canonical = Path(CANONICAL_STORE).resolve()
            for child in skills.iterdir():
                if child.is_symlink() and child.resolve().is_relative_to(canonical):
                    _add(
                        actions,
                        seen,
                        "symlink",
                        child,
                        "skill link into canonical managed skill store",
                    )
            _add(actions, seen, "dir-if-empty", skills, "generated skills directory")
    if "codegraph" in steps:
        _add(
            actions,
            seen,
            "dir",
            root / ".codegraph",
            "regenerable CodeGraph cache/index",
            "cache",
        )
    if "pi" in steps:
        for path in (
            root / ".pi" / "agent" / name
            for name in ("settings.json", "models.json", "auth.json")
        ):
            _add(actions, seen, "file", path, "generated Pi project configuration")
        _add(
            actions,
            seen,
            "dir-if-empty",
            root / ".pi" / "agent",
            "generated Pi directory",
        )
        for name in ("extensions", "skills"):
            _add(
                actions,
                seen,
                "dir-if-empty",
                root / ".pi" / name,
                "generated Pi directory",
            )
        _add(actions, seen, "dir-if-empty", root / ".pi", "generated Pi root directory")
    if "jetbrains" in steps or "junie" in steps:
        junie = root / ".junie"
        if junie.is_symlink() and junie.resolve() == (root / ".ai").resolve():
            _add(actions, seen, "symlink", junie, "generated .junie link to .ai")
        elif junie.exists() or junie.is_symlink():
            logger.warning("Keeping non-generated .junie at %s", junie)
        assistant = root / ".aiassistant"
        rules = assistant / "rules"
        if rules.is_symlink() and rules.resolve() == (root / ".ai" / "rules").resolve():
            _add(actions, seen, "symlink", rules, "generated JetBrains rules link")
        _add(
            actions, seen, "dir-if-empty", assistant, "generated AI Assistant directory"
        )
        ai = root / ".ai"
        if "mcps" in steps:
            _add(
                actions,
                seen,
                "file",
                ai / "mcp" / "mcp.json",
                "generated JetBrains MCP config",
            )
        for name in ("mcp", "review", "agents", "rules"):
            _add(
                actions,
                seen,
                "dir-if-empty",
                ai / name,
                "generated JetBrains AI directory",
            )
        logger.info(
            "Submodule JetBrains links are out of scope for workspace-root cleanup."
        )
    if "mcps" in steps:
        if "jetbrains" not in steps and "junie" not in steps:
            _add(
                actions,
                seen,
                "file",
                root / ".ai/mcp/mcp.json",
                "generated project MCP config",
            )
            _add(
                actions,
                seen,
                "dir-if-empty",
                root / ".ai/mcp",
                "generated JetBrains MCP directory",
            )
        names = _known_mcp_names()
        paths = [
            root / ".cursor/mcp.json",
            root / ".gemini/settings.json",
            root / ".claude/mcp.json",
            root / ".claude/claude_desktop_config.json",
            root / ".mcp.json",
            root / ".pi/mcp.json",
            root / ".cline/mcp.json",
            root / ".snowflake/cortex/mcp.json",
            root / ".agents/mcp_config.json",
            root / ".vscode/mcp.json",
        ]
        for path in paths:
            if path.exists() and _merge_file_is_generated(path, names):
                _add(
                    actions,
                    seen,
                    "file",
                    path,
                    "project MCP merge containing only known generated servers",
                )
            elif path.exists():
                logger.warning("Keeping MCP file with user content: %s", path)
        logger.info(
            "Leaving Codex project TOML untouched; it may contain user configuration."
        )
    return actions


def _size(path):
    return sum(item.stat().st_size for item in path.rglob("*") if item.is_file())


def execute_cleanup(actions):
    """Run actions in safe order; files/symlinks first, then dirs, deepest-first.

    dir-if-empty actions must run after the files that empty them, so actions
    are re-sorted here rather than relying on plan order.
    """
    order = {"file": 0, "symlink": 0, "dir": 1, "dir-if-empty": 2}
    ranked = sorted(
        enumerate(actions),
        key=lambda item: (
            order.get(item[1]["kind"], 3),
            # deepest paths first so parent pruning sees emptied children
            -item[1]["path"].count(os.sep),
            item[0],
        ),
    )
    counts = {"removed": 0, "kept": 0, "skipped": 0}
    categories = {}
    for _, action in ranked:
        path = Path(action["path"])
        category = categories.setdefault(
            action["safety_class"], {"removed": 0, "kept": 0, "skipped": 0}
        )
        try:
            if action["kind"] in {"file", "symlink"}:
                path.unlink()
            elif action["kind"] == "dir-if-empty":
                path.rmdir()
            else:
                shutil.rmtree(path)
            logger.info(f"Removed {path}")
            counts["removed"] += 1
            category["removed"] += 1
        except OSError as exc:
            logger.warning(f"Kept {path}: {exc}")
            if path.is_dir() and action["kind"] == "dir-if-empty":
                remaining = sorted(str(child) for child in path.iterdir())
                if remaining:
                    logger.warning("Content remains: " + ", ".join(remaining))
            counts["kept"] += 1
            category["kept"] += 1
    return counts, categories


def main():
    parser = argparse.ArgumentParser(
        description="Clean project-scoped AI-tooling artefacts."
    )
    add_common_args(parser)
    parser.add_argument("--workspace-root", default=os.getcwd())
    parser.add_argument(
        "--steps", default=None, help=f"Comma-separated steps (default: all)"
    )
    add_skip_arg(parser, ALL_STEPS)
    parser.add_argument(
        "--force", action="store_true", help="Skip confirmation prompts."
    )
    args = parser.parse_args()
    load_env()  # Best effort; cleanup does not require secrets.
    steps = csv(args.steps) if args.steps is not None else list(ALL_STEPS)
    unknown = set(steps) - set(ALL_STEPS)
    if unknown:
        parser.error(f"Unknown step(s): {', '.join(sorted(unknown))}")
    steps = [step for step in steps if step not in parse_skip(args.skip, ALL_STEPS)]
    actions = plan_cleanup(args.workspace_root, steps)
    root_config = Path(args.workspace_root).resolve() / "opencode.json"
    if (
        "opencode" in steps
        and args.force
        and root_config.exists()
        and not root_config.is_symlink()
        and str(root_config) not in {action["path"] for action in actions}
    ):
        actions.insert(
            0,
            _action(
                "file",
                root_config,
                "forced removal of project OpenCode config",
                "forced",
            ),
        )
    if not actions:
        logger.info("No managed project artefacts found.")
        return
    risky = [action for action in actions if action["kind"] in {"symlink", "dir"}]
    for action in actions:
        detail = (
            f" ({_size(Path(action['path']))} bytes)"
            if action["path"].endswith(".codegraph")
            else ""
        )
        logger.info(f"Would remove {action['path']}: {action['reason']}{detail}")
    if args.dry_run:
        logger.info(f"Dry run: {len(actions)} action(s) planned, nothing removed.")
        return
    if risky and not args.force:
        try:
            answer = input("Continue? [y/N] ")
        except EOFError:
            answer = ""
        if answer.strip().lower() != "y":
            logger.info("Cleanup cancelled.")
            return
    counts, categories = execute_cleanup(actions)
    summary = [
        "Cleanup summary:",
        *(f"  {key}: {value}" for key, value in counts.items()),
    ]
    summary.extend(
        f"  {name}: removed={values['removed']} kept={values['kept']} skipped={values['skipped']}"
        for name, values in sorted(categories.items())
    )
    logger.info("\n".join(summary))


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, OSError, ValueError, json.JSONDecodeError) as exc:
        logger.critical(str(exc))
        raise SystemExit(1)
